#20170130
#Flora Tsai


ocr: mnist.h mnist.c distance.h distance.c euclid.c reduced.c downsample.c crop.c threshold.c knn.h knn.c ocr.c
	gcc -Wall -Werror -pedantic -std=c11 mnist.c euclid.c reduced.c downsample.c crop.c threshold.c distance.c knn.c ocr.c -o ocr

clean: ocr
	rm ocr
